import { StyleSheet } from 'react-native';
import { appColors } from '../../../constants/appColors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 30,
        paddingBottom: 20,
        paddingHorizontal: 10,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5E5',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(255, 255, 255, 0.12)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    headerInfo: {
        flex: 1,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#000',
        marginBottom: 4,
    },
    headerSubtitle: {
        fontSize: 14,
        color: '#666',
    },
    tabContainer: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5E5',
    },
    tab: {
        flex: 1,
        paddingVertical: 16,
        alignItems: 'center',
    },
    activeTab: {
        borderBottomWidth: 2,
        borderBottomColor: appColors.primary,
    },
    tabText: {
        fontSize: 16,
        color: '#666',
    },
    activeTabText: {
        color: appColors.primary,
        fontWeight: '600',
    },
    tabContent: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    summaryContainer: {
        padding: 20,
    },
    summaryCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    summaryInfo: {
        flex: 1,
    },
    summaryLabel: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
    },
    summaryValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: appColors.primary,
        marginBottom: 4,
    },
    summaryTotal: {
        fontSize: 14,
        color: '#666',
    },
    filterButtons: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    filterButton: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#E5E5E5',
        backgroundColor: '#FFFFFF',
        marginRight: 12,
    },
    activeFilter: {
        backgroundColor: appColors.primary,
        borderColor: appColors.primary,
    },
    filterButtonText: {
        fontSize: 14,
        color: '#666',
    },
    activeFilterText: {
        color: '#FFFFFF',
    },
    chartContainer: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 20,
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    chartHeader: {
        
    },
    chartLegend: {
        flexDirection: 'column',
        gap: 8,
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    legendDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginRight: 8,
    },
    legendText: {
        fontSize: 14,
        color: '#666',
    },
    chart: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        height: 120,
        marginTop: 20,
    },
    chartColumn: {
        alignItems: 'center',
        flex: 1,
    },
    chartBar: {
        width: 20,
        height: 100,
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    revenueBar: {
        width: 8,
        borderRadius: 4,
        marginRight: 2,
    },
    ticketBar: {
        width: 8,
        borderRadius: 4,
        marginLeft: 2,
    },
    chartLabel: {
        fontSize: 12,
        color: '#666',
        marginTop: 8,
        transform: [{ rotate: '-45deg' }],
    },
    checkinButtons: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        paddingTop: 20,
        marginBottom: 20,
    },
    checkinButton: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#E5E5E5',
        backgroundColor: '#FFFFFF',
        marginRight: 12,
    },
    activeCheckinButton: {
        backgroundColor: appColors.primary,
        borderColor: appColors.primary,
    },
    checkinButtonText: {
        fontSize: 14,
        color: '#666',
    },
    activeCheckinButtonText: {
        color: '#FFFFFF',
    },
    checkinSummary: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 20,
        borderRadius: 16,
        padding: 20,
        marginTop: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    eventStats: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 20,
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    statItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    statInfo: {
        marginLeft: 12,
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    statLabel: {
        fontSize: 16,
        color: '#333',
    },
    statValue: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginHorizontal: 20,
        marginBottom: 16,
    },
    ticketTypeCard: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 20,
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    ticketTypeName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    searchContainer: {
        paddingHorizontal: 20,
        paddingTop: 20,
        marginBottom: 16,
    },
    searchInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 25,
        paddingHorizontal: 16,
        paddingVertical: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    searchIcon: {
        marginRight: 12,
    },
    searchPlaceholder: {
        fontSize: 16,
        color: '#666',
    },
    orderFilters: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        marginBottom: 16,
    },
    orderFilter: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#E5E5E5',
        backgroundColor: '#FFFFFF',
        marginRight: 12,
    },
    activeOrderFilter: {
        backgroundColor: appColors.primary,
        borderColor: appColors.primary,
    },
    orderFilterText: {
        fontSize: 14,
        color: '#666',
    },
    activeOrderFilterText: {
        color: '#FFFFFF',
    },
    orderCount: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        marginHorizontal: 20,
        marginBottom: 16,
    },
    ordersList: {
        flex: 1,
        paddingHorizontal: 20,
    },
    orderItem: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    orderHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    customerName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
    },
    orderId: {
        fontSize: 14,
        color: '#666',
        marginBottom: 12,
    },
    orderDetails: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    orderDetailColumn: {
        flex: 1,
    },
    orderDetailLabel: {
        fontSize: 12,
        color: '#666',
        marginBottom: 4,
    },
    orderDetailValue: {
        fontSize: 14,
        color: '#333',
    },
});